# Generated by Django 4.1 on 2024-03-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoppingcart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
