# Generated by Django 4.1 on 2024-03-17 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shoppingcart", "0002_cart_quantity_delete_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="quantity",
        ),
    ]
