# Generated by Django 4.1 on 2024-03-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("size", models.CharField(max_length=255)),
                (
                    "image_prodcut",
                    models.ImageField(
                        default="media/products/images/box.jpg",
                        upload_to="products/images/",
                    ),
                ),
                ("price", models.IntegerField()),
            ],
        ),
    ]
