# Generated by Django 4.1 on 2024-03-16 22:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_rename_image_prodcut_product_image_products"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image_products",
            new_name="image_product",
        ),
    ]
