# Generated by Django 4.1 on 2024-03-17 06:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="shopping_cart",
        ),
    ]
