# Generated by Django 5.0.2 on 2024-03-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_remove_product_quantity_remove_product_shopping_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_product",
            field=models.ImageField(
                default="products/images/box.jpg", upload_to="products/images/"
            ),
        ),
    ]
